name: portfolio
description: A beautifully crafted portfolio site built with flutter

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^6.3.2
  responsive_builder: ^0.7.1
  font_awesome_flutter: ^10.9.1 
  url_launcher: ^6.3.1
  flutter_feather_icons: ^2.0.0+1 
  animated_text_kit: ^4.2.1
  visibility_detector: ^0.4.0+2
  flutter_bloc: ^9.1.1
  layout: ^1.0.5
  freezed_annotation: ^3.1.0
  dartz: ^0.10.0
  get_it: ^8.2.0
  flutter_spinkit: ^5.0.0

  cupertino_icons: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  freezed: ^3.2.3

flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/projects/
    - assets/images/projects/aerium-v1/
    - assets/images/projects/aerium-v2/
    - assets/images/projects/disneyplus/
    - assets/images/projects/drop/
    - assets/images/projects/flutter_catalog/
    - assets/images/projects/foodybite/
    - assets/images/projects/login_catalog/
    - assets/images/projects/nimbus/
    - assets/images/projects/otp_package/
    - assets/images/projects/roam/
    - assets/images/projects/outfitr/
    - assets/screenshots/
  #    - assets/screenshots/


  fonts:
    - family: VisueltPro
      fonts:
        - asset: assets/fonts/visuelt/VisueltPro-Thin.ttf
          weight: 100
        - asset: assets/fonts/visuelt/VisueltPro-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/visuelt/VisueltPro-Light.ttf
          weight: 300
        - asset: assets/fonts/visuelt/VisueltPro-Regular.ttf
          weight: 400
        - asset: assets/fonts/visuelt/VisueltPro-Medium.ttf
          weight: 500
        - asset: assets/fonts/visuelt/VisueltPro-Black.ttf
          weight: 700
        - asset: assets/fonts/visuelt/VisueltPro-Bold.ttf
          weight: 800
   